# Generated by Django 3.1.14 on 2025-01-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20250125_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='Defense',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='Health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='Level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='Stamina',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='Strength',
            field=models.IntegerField(default=10),
        ),
    ]
